tags:
  idam-pr: false

ingressHost: chart-ccd-release.service.core-compute-preview.internal
ingressIP: "10.97.17.51"
consulIP: "10.97.11.254"

readinessDelay: 90
livenessDelay: 90

global:
  idamApiUrl: https://idam-api.aat.platform.hmcts.net
  idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
  environment: aat