dependencies:
  - name: rd-user-profile-api
    version: ~0.0.5
    repository: '@hmctspublic'
  - name: rpe-service-auth-provider
    version: ~0.2.0
    repository: '@hmctspublic'
  - name: postgresql
    version: ~6.3.5
    repository: '@stable'