dependencies:
  - name: rd-user-profile-api
    version: ~0.0.6
    repository: '@hmctspublic'
    condition: rd.rd-user-profile-api.enabled
  - name: rd-professional-api
    version: ~0.0.4
    repository: '@hmctspublic'
    condition: rd.rd-professional-api.enabled
  - name: rd-profile-sync
    version: ~0.0.4
    repository: '@hmctspublic'
    condition: rd.rd-profile-sync.enabled
  - name: rpe-service-auth-provider
    version: ~0.2.5
    repository: '@hmctspublic'
    condition: rd.rpe-service-auth-provider.enabled
  - name: postgresql
    version: ~6.3.5
    repository: '@stable'
    condition: rd.postgresql.enabled