java:
  applicationPort: 8091
  ingressHost: rd-user-profile-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: rd
  image: 'hmctspublic.azurecr.io/rd/user-profile-api:latest'
  environment:
    POSTGRES_HOST: rd-user-profile-api-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_USERNAME: dbuserprofile@rd-user-profile-api-postgres-db-{{ .Values.global.environment }}
    POSTGRES_NAME: dbuserprofile
    POSTGRES_PORT: 5432
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  keyVaults:
    rd:
      secrets:
        - s2s-secret
        - user-profile-api-POSTGRES-PASS
        - AppInsightsInstrumentationKey
postgresql:
  # Due to stability issues in the Preview environment, please disable persistance in the consuming chart for the Preview environment.
  persistence:
    enabled: true
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "dbuserprofile" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  postgresqlDatabase: rd

rpe-service-auth-provider:
  java:
    ingressHost: ""
    releaseNameOverride: service-auth-s2s
    readinessDelay: 180
    livenessDelay: 180
    keyVaults:
    environment:
      TESTING_SUPPORT_ENABLED: 'true'
      MICROSERVICEKEYS_CCD_ADMIN: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_DATA: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_DEFINITION: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_GW: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_PS: AAAAAAAAAAAAAAAA
